server:
 port: 8086
spring:
 data:
  mongodb:
    database: mongodb
 kafka:
  consumer:
    group-id: 1
    bootstrap-servers: localhost:9092
    value-deserializer: ru.innowise.danko.notification.util.EventDeserializer
    properties:
      spring.json.trusted.packages: "*"
    auto-offset-reset: earliest
    enable-auto-commit: false